# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(454, 400)
        MainWindow.setFixedSize(454, 400)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(160, 30, 160, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(True)
        self.title.setFont(font)
        self.title.setObjectName("title")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 70, 300, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")

        self.inputName = QtWidgets.QLineEdit(self.centralwidget)
        self.inputName.setGeometry(QtCore.QRect(100, 140, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.inputName.setFont(font)
        self.inputName.setText("")
        self.inputName.setObjectName("inputName")

        self.inputPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPassword.setGeometry(QtCore.QRect(100, 180, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.inputPassword.setFont(font)
        self.inputPassword.setText("")
        self.inputPassword.setObjectName("inputPassword")
        self.inputPassword.setEchoMode(QtWidgets.QLineEdit.Password)

        self.registrationBox = QtWidgets.QCheckBox(self.centralwidget)
        self.registrationBox.setGeometry(QtCore.QRect(100, 215, 241, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registrationBox.setText('Регистрация')

        self.title_URL = QtWidgets.QLabel(self.centralwidget)
        self.title_URL.setGeometry(QtCore.QRect(100, 250, 240, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setKerning(True)
        self.title_URL.setFont(font)
        self.title_URL.setObjectName("title")

        self.URLInput = QtWidgets.QLineEdit(self.centralwidget)
        self.URLInput.setGeometry(QtCore.QRect(100, 280, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.URLInput.setFont(font)
        self.URLInput.setObjectName("URLInput")

        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(100, 330, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")

        self.errorText = QtWidgets.QLabel(self.centralwidget)
        self.errorText.setGeometry(QtCore.QRect(100, 370, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.errorText.setFont(font)
        self.errorText.setStyleSheet("color: #7F0000;")
        self.errorText.setText("")
        self.errorText.setObjectName("errorText")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Авторизация"))
        self.title.setText(_translate("MainWindow", "Авторизация"))
        self.title_URL.setText(_translate("MainWindow", "Адрес сервера PKG:"))
        self.inputName.setPlaceholderText(_translate("MainWindow", "Имя"))
        self.loginButton.setText(_translate("MainWindow", "Далее"))
        self.URLInput.setText(_translate("MainWindow", "185.124.152.99:4180"))
        self.URLInput.setPlaceholderText(_translate("MainWindow", "Сервер чата"))
        self.inputPassword.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Поставьте галочку для регистрации, <br/>если аккаунт не существует</p></body></html>"))
